### ISSUE TITLE
THEA - "Dont show again" for popup tutorial is not working

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#536] opened 2023-06-23 12:42 UTC
"Dont show again" for popup tutorial is not working

https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/assets/6218678/b9b10c5b-86ed-4d4b-b284-d287b634acfe

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by ap211unitech** [comment] 2023-06-26 05:35
Duplicate of https://github.com/Polkadex-Substrate/Polkadex-Open-Beta/issues/533

**Closed** 2023-06-27 10:06 UTC
Labels: Unconfirmed, May16-June29-2023
