### ISSUE TITLE
Feedback to add Sort

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#190] opened 2022-07-12 15:47 UTC
Feedback to add Sort option in Transaction Grid. Currently the columns cannot be sorted.

onchainaddress:{espoXXdCqhP6oRPbP5avJhcZi6LNFyUCnDumF3cUPwops32FN}

![image](https://user-images.githubusercontent.com/94037805/178533534-5835117f-bee8-4f0e-8459-ebf1368395d6.png)

**Comment by mastervalidator** [comment] 2022-07-12 23:10
duplicate #98

**Comment by pavankanteti** [comment] 2022-07-26 07:17
Closing as duplicate of #98

**Closed by pavankanteti** 2022-07-26 07:17 UTC
Labels: duplicate, Unconfirmed
