### ISSUE TITLE
Market Order not working 

### ISSUE THREAD

**Issue by davesanna** [Polkadex-Substrate/Polkadex-Open-Beta#336] opened 2022-10-01 13:03 UTC
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

It is not possible to execute a market order (in the example, trying to sell at market price PDEX for FAU).

![Screen Recording](https://user-images.githubusercontent.com/81797664/193410677-b5336fcf-bf23-4133-9a6b-b4705e94d209.mov)

https://user-images.githubusercontent.com/81797664/193410677-b5336fcf-bf23-4133-9a6b-b4705e94d209.mov

onchainaddress:{esr7bFqhupjASG4tXqEcLs6xDhU81jw5U8HYZ7AMYbSkw2RjS}

**Comment by jaymansfield** [comment] 2022-10-01 15:12
Duplicate of #265

**Comment by nuel77** [comment] 2022-10-03 07:19
The number of decimals in the qty payload is more that what the trading pair configuration is set for. The qty should only be incremented by step size.

**Comment by nuel77** [comment] 2022-10-03 07:21
> Duplicate of #265

not a duplicate. The error shown are different. #265 is marketliquidityerror and this is qty step size error.

**Comment by charleslukes** [comment] 2022-10-06 11:08
fixed in https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/pull/359

**Closed** 2022-10-06 11:14 UTC
Labels: Unconfirmed, Aug19-Oct2
