### ISSUE TITLE
Cannot import my account. Getting 500 error.

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#84] opened 2022-07-06 12:23 UTC
Cannot import my account. Getting 500 error.

![image](https://user-images.githubusercontent.com/94037805/177549304-68fb0f46-f2b1-40a3-8c82-fc43c9930195.png)

**Comment by jaymansfield** [comment] 2022-07-06 12:46
Duplicate #5

**Comment by pavankanteti** [comment] 2022-07-07 03:59
Closing as duplicate of #5

**Closed by pavankanteti** 2022-07-07 03:59 UTC
Labels: duplicate, Unconfirmed
