### ISSUE TITLE
Both main account and trading get disconnected if I reload the browser

### ISSUE THREAD

**Issue by LunaPolkadex** [Polkadex-Substrate/Polkadex-Open-Beta#225] opened 2022-08-23 23:16 UTC
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 
Everytime I reload the browser both my main AND trading account get disconnected and i need to select them again.

**Note** : Make sure you add the screenshot using Markdown syntax, For example: `![Alt Text](Screenshot Url)`

onchainaddress:{esnpHCUii7PvrGr5d3r2LLSseXzbKteTAsxLGHhhptmL9m4uJ}

**Comment by jaymansfield** [comment] 2022-08-23 23:26
#2

**Comment by pavankanteti** [comment] 2022-11-15 08:18
closing as duplicate of #2

**Closed by pavankanteti** 2022-11-15 08:18 UTC
Labels: duplicate, Verified Author, Aug19-Oct2
