### ISSUE TITLE
Registration is resetting without cache clearance

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#389] opened 2022-11-11 08:50 UTC
My registrations are gone. I had closed the browser and reopened the url : https://orderbook-beta.polkadex.trade/sign
I had NOT cleared cache also. But it shows all my funding accounts as not registered. Both were registered just 2 hours back or so!!
onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}

![image](https://user-images.githubusercontent.com/94037805/201302290-a3bb8c3d-dd26-42fd-91ca-f601fd8ace6e.png)

**Comment by DayalKS2** [comment] 2022-11-11 08:53
Now when I tried to re-register I am getting below error saying this account is already registered.

![image](https://user-images.githubusercontent.com/94037805/201303074-d6ca1fa7-043c-417c-9c3d-29def4c5dc78.png)

**Comment by DayalKS2** [comment] 2022-11-11 12:30
Due to this issue, I am unable to re-register and hence lost all fund tagged to my account...I had many withdrawals left for Claim

**Comment by nuel77** [comment] 2022-11-11 13:15
did you get any error when you registered these accounts the first time?

**Comment by DayalKS2** [comment] 2022-11-11 13:40
No these accounts were perfectly fine when I registered them today morning.
I was able to make few transactions without any issues. Then when I was
testing the WITHDRAW flows for negative use cases (384 and 385 tickets), I
got few errors for withdrawal. But after that I started getting Error
screens which I reported under 386 which stopped me from even navigating
from one page to another. Since there was no escape, I closed the
browser and re-opened the url (https://orderbook-beta.polkadex.trade/sign).
This time I could see that all my registrations got wiped away. So I tried
re-registering and that failed as well saying the addresses are already
registered.

**Comment by nuel77** [comment] 2022-11-11 17:13
can you check the console when you get the unknown error while switching pages.. it should show up there.

**Comment by DayalKS2** [comment] 2022-11-12 09:17
The recording should have it.  Please see below text, screenshot and recording. 

Failed to load resource: the server responded with a status of 401 () kckpespz5bb2rmdnuxycz6e7he.appsync-api.eu-central-1.amazonaws.com/graphql:1
_app-a2656640edd71895.js:1 Error: getAllMainLinkedAccounts Array(1)
_app-a2656640edd71895.js:1 User error TypeError: Cannot read properties of undefined (reading 'accounts')
    at _app-a2656640edd71895.js:1:1599754
    at s (main-1bfbdd436558a21e.js:1:73302)
    at Generator._invoke (main-1bfbdd436558a21e.js:1:73090)
    at forEach.e.<computed> [as next] (main-1bfbdd436558a21e.js:1:73725)
    at r (_app-a2656640edd71895.js:1:2500821)
    at s (_app-a2656640edd71895.js:1:2501024)
![image](https://user-images.githubusercontent.com/94037805/201467490-085d3e06-b7d5-45c0-9e3f-e89683f5fc68.png)

https://user-images.githubusercontent.com/94037805/201467239-2efea0b7-780d-45d4-93ae-e373d4a192ce.mp4

**Comment by nuel77** [comment] 2022-11-12 19:33
i think this issue and #411 are releated.

**Comment by nuel77** [comment] 2022-11-12 19:47
can you open this Array(1) here? that has more info regarding what is causing this..
<img width="520" alt="image" src="https://user-images.githubusercontent.com/50878033/201491926-1931c8f7-5071-45f5-9dc1-ac43b347baf4.png">

**Comment by pavankanteti** [comment] 2022-11-16 06:57
duplicate of #411

**Closed by pavankanteti** 2022-11-16 06:57 UTC
Labels: duplicate, Unconfirmed, Oct3-Nov16
