### ISSUE TITLE
Deposit ETH - "arithmetic":"Underflow"

### ISSUE THREAD

**Issue by jcbm123143** [Polkadex-Substrate/Polkadex-Open-Beta#135] opened 2022-07-07 08:33 UTC
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 
Deposit ETH - "arithmetic":"Underflow"

![image](https://user-images.githubusercontent.com/22148449/177728781-3026c336-6bdf-49c7-b83f-ed83eede50a6.png)

I try to deposit 1000000 ETH
**Error Message Show  {"arithmetic":"Underflow"}**

onchainaddress:{esr4zxY2vA6RqqMPppdTMEu313UDe9q8UVu8JZpZrucefyyzZ}

**Comment by jcbm123143** [comment] 2022-07-07 08:35
onchainaddress:{esr2nHao5bppqUBUfvN8oyCYAD66CxhwaDfVhatsYCkXcy75d}

**Comment by jaymansfield** [comment] 2022-07-07 11:39
#34

**Comment by pavankanteti** [comment] 2022-07-12 05:53
duplicate of #34

**Closed by pavankanteti** 2022-07-12 05:53 UTC
Labels: duplicate, Unconfirmed
