### ISSUE TITLE
Notification center issue with mark as read

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#278] opened 2022-09-29 15:26 UTC
In notification center, when I mark one notification as 'Mark as Read', all the unread messages are moved to Mark as Read. Not sure this is as per design or a bug? If its as per design, I don't understand giving the control to mark as Read at a message level.

onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}

**Comment by jaymansfield** [comment] 2022-09-29 15:35
Duplicate of #219

**Comment by pavankanteti** [comment] 2022-11-17 13:55
closing as duplicate of #219

**Closed by pavankanteti** 2022-11-17 13:55 UTC
Labels: Unconfirmed, Aug19-Oct2
