### ISSUE TITLE
Show only Selected Coin is not working in Withdraw Crypto

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#291] opened 2022-09-30 02:23 UTC
Show only Selected Coin is not working in Withdraw Crypto

onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}

![image](https://user-images.githubusercontent.com/94037805/193176463-c560f3de-fbf0-419b-890f-1d44e8ebda91.png)

**Comment by jaymansfield** [comment] 2022-09-30 12:59
Duplicate of #264

**Closed** 2022-11-17 14:14 UTC
Labels: Unconfirmed, Aug19-Oct2
