### ISSUE TITLE
Buy Limit Order "Error"

### ISSUE THREAD

**Issue by jcbm123143** [Polkadex-Substrate/Polkadex-Open-Beta#143] opened 2022-07-07 10:34 UTC
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

Buy Limit Order "Error"
I set the order Price of 0.1111 and 1 amount

Error message show
**Error
Trade volume not within limits: min: 1000000000000, max: 1000000000000000**

![image](https://user-images.githubusercontent.com/22148449/177753818-ea069d72-2136-4ba8-a09d-07a64835f631.png)

onchainaddress:{esr4zxY2vA6RqqMPppdTMEu313UDe9q8UVu8JZpZrucefyyzZ}

**Comment by pavankanteti** [comment] 2022-09-21 09:05
Unable to reproduce the described error. The errors in the image are duplicates. Hence closing.

**Closed by pavankanteti** 2022-09-21 09:05 UTC
Labels: duplicate, Unconfirmed, FrontEnd, immediate fix, high priority, July4-Aug18
