### ISSUE TITLE
Cannot import the seed and cannot connect to my js wallet

### ISSUE THREAD

**Issue by caorenzhi** [Polkadex-Substrate/Polkadex-Open-Beta#149] opened 2022-07-07 18:58 UTC
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

My video: https://www.youtube.com/watch?v=9VXQ2QkiF98
I would like to report a few issues: 
1. The users cannot claim the test token more than once
2. We cannot import seed word in the orderbook website, I have tried to copy the seed or type it manually
3. There should be an option to connect to my js account in the orderbook website, but right now I don't see that option, and since I cannot import seed word as well, I cannot move forward to test the other functions. 

**Note** : Make sure you add the screenshot using Markdown syntax, For example: `![Alt Text](Screenshot Url)`

onchainaddress:{esmTCfxdKpYDgC75L8biiEofg5pCvjxwE56XujB4HsUjSYSdG}

**Comment by pavankanteti** [comment] 2022-07-08 14:18
duplicate of #5

**Closed by pavankanteti** 2022-07-08 14:18 UTC
Labels: duplicate, Unconfirmed
