### ISSUE TITLE
Error 500 on account recovery request

### ISSUE THREAD

**Issue by mastervalidator** [Polkadex-Substrate/Polkadex-Open-Beta#65] opened 2022-07-05 00:12 UTC
By raising this issue, I agree to the terms and conditions presented by Polkadex here:[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf)

Description
-Error 500 on account recovery request, generating wrong address from the mnemonics

![image](https://user-images.githubusercontent.com/108701680/177227269-e229b819-7b5f-494c-87de-4004f8332946.png)

onchainaddress:{esqD5TsdP2UPmxsBZWEP5iTb73ZPW5mf9RSXsEoP6kw8bXW2Z}

**Comment by jaymansfield** [comment] 2022-07-05 00:45
Might be a duplicate of #5

**Comment by pavankanteti** [comment] 2022-07-06 11:53
Closing as duplicate of #5

**Closed by pavankanteti** 2022-07-06 11:53 UTC
Labels: duplicate, Unconfirmed, Verified Author
