### ISSUE TITLE
Open Orders, Order History, Trade History

### ISSUE THREAD

**Issue by Dude0609** [Polkadex-Substrate/Polkadex-Open-Beta#126] opened 2022-07-06 15:35 UTC
An error message appears when checking the open order, order history and trade history tabs. 

onchainaddress: {esoiFAMrCMufzPxBnybkhFsXWP3P5K6x4yeCEBz1q8jwSwbra}

**Comment by pavankanteti** [comment] 2022-09-21 08:24
Not enough data. Unable to reproduce. Hence closing.

**Closed by pavankanteti** 2022-09-21 08:24 UTC
Labels: wontfix, Unconfirmed, July4-Aug18
