### ISSUE TITLE
History is blank for me

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#36] opened 2022-07-04 18:45 UTC
I have done many Deposits (4 or 5) from my wallet to Proxy account. I don't see those balance in my Proxy account. Neither my transactions are shown in the History section. History section is blank.

onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}

![History is blank](https://user-images.githubusercontent.com/94037805/177205346-2ecc3d07-b46e-4bd3-a276-0e2b44cec9be.png)

**Comment by DayalKS2** [comment] 2022-07-06 12:29
I wish I could. But since I have cleared up my browsing history I am locked that I am no longer seeing my Proxy Account displayed in Sign In page. Neither can I create new accounts NOR I can register another account by suing new account in my polkadot.js extension. So I am locked from Testing as I cannot access. Importing with right mneumonics also failed as I am getting 500 error.

To address the reported issue, Yes I was not seeing any transactions in my history. One quick question, when user clicks Wallet the attached screen appeared. In the dropdown I am seeing my Polkadex Mainnet address and not my proxy account. Is this correct behaviour?

**Comment by pavankanteti** [comment] 2022-09-15 06:23
Closing as we're unable to reproduce and also tested and verified in the new implementation.

**Closed by pavankanteti** 2022-09-15 06:23 UTC
Labels: Unconfirmed, July4-Aug18
