### ISSUE TITLE
Deleting Trading Account Leaves Orphaned Orders

### ISSUE THREAD

**Issue by mt-gareth** [Polkadex-Substrate/Polkadex-Open-Beta#439] opened 2022-11-28 20:10 UTC
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

If you have a trading account and delete it from the blockchain the orders that are on that account remain open and unable to be canceled. This can happen if the key to the trading account is lost and removed in local storage, the owner would have no way to cancel the orders on that account.

I was able to reproduce this by making a trading account, making an order on that account, and then deleting that account from the blockchain, my order remained and I am unable to cancel the order.

onchainaddress:{esrCussMhQXzcYQfHkrRFYwfUJq6bfQ4yDg6vbnF2KtpSAqRu}

**Comment by jaymansfield** [comment] 2022-11-29 12:27
Raised already here #414

**Comment by pavankanteti** [comment] 2023-02-15 10:37
Closing as duplicate of #414

**Closed by pavankanteti** 2023-02-15 10:37 UTC
Labels: duplicate, Verified Author, Nov17-Dec31
