### ISSUE TITLE
chechboxes don't work

### ISSUE THREAD

**Issue by TotolAstico** [Polkadex-Substrate/Polkadex-Open-Beta#153] opened 2022-07-08 18:16 UTC
the checkboxes do not update the order history, trade history and the open orders.
The drop-down menu does not update either. 

onchainaddress:{esmSs5Lx2my8DK3yk41Xfb7Gp4M13jAf5rCuLUDB3BmaJuupp}

**Comment by pavankanteti** [comment] 2022-07-12 15:09
duplicate of #118

**Closed by pavankanteti** 2022-07-12 15:09 UTC
Labels: duplicate, Unconfirmed
