### ISSUE TITLE
Sorting Not Working

### ISSUE THREAD

**Issue by jcbm123143** [Polkadex-Substrate/Polkadex-Open-Beta#138] opened 2022-07-07 10:00 UTC
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

Sorting Not Working - **"Hide" "Other" "Pairs" "Buy" "Sell" "All Transaction"** Not functioning

![image](https://user-images.githubusercontent.com/22148449/177746739-49aad6c8-d74a-4147-9a40-6401b0b25398.png)

onchainaddress:{esr4zxY2vA6RqqMPppdTMEu313UDe9q8UVu8JZpZrucefyyzZ}

**Comment by pavankanteti** [comment] 2022-07-08 12:05
duplicate of #106

**Closed by pavankanteti** 2022-07-08 12:05 UTC
Labels: duplicate, Unconfirmed
