### ISSUE TITLE
Chart calendar text dropdowns not following Theme toggle

### ISSUE THREAD

**Issue by arrow-aal** [Polkadex-Substrate/Polkadex-Open-Beta#198] opened 2022-07-16 20:26 UTC
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

Chart calendar dropdowns not being displayed following the Dark mode theme.

![Calendar Month selector](https://user-images.githubusercontent.com/109436633/179370918-52cf9acb-1f58-4fc6-ae8b-dc03b340fa30.png)

![Calendar year selector](https://user-images.githubusercontent.com/109436633/179370919-13320341-56cf-4697-9d24-ec195b4cedd7.png)

onchainaddress:{Insert your onchain address within the braces without any spaces}

**Comment by pavankanteti** [comment] 2022-09-23 06:19
Closing as duplicate of #119

**Closed by pavankanteti** 2022-09-23 06:19 UTC
Labels: duplicate, Unconfirmed, immediate fix, UI, July4-Aug18
