### ISSUE TITLE
Withdraw tabs - date wrong

### ISSUE THREAD

**Issue by Targan23** [Polkadex-Substrate/Polkadex-Open-Beta#451] opened 2023-01-20 10:52 UTC
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

On the 3rd Tab for History (Claimed) the date is automatically set to the current date. (12:50)

![image](https://user-images.githubusercontent.com/34280398/213677991-ae5020b2-9022-4606-b131-276d3b87a0df.png)

If i refresh the page the date changes. (12:51)

![image](https://user-images.githubusercontent.com/34280398/213678078-b9562ae8-c035-4616-b6f5-1e3d393c1d57.png)

P.S. That 2 PDEX withdrawal is months old

onchainaddress:{esouQaHBfnppyHJT7kjmk7BhtL3f9HFgNpnHCqqSpYKcGKwb3}

**Comment by jaymansfield** [comment] 2023-01-30 19:32
Duplicate of #295

**Comment by pavankanteti** [comment] 2023-04-03 06:43
closing as duplicate

**Closed by pavankanteti** 2023-04-03 06:43 UTC
Labels: duplicate, Jan1-Feb14
