### ISSUE TITLE
Unable to Cancel Open Orders

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#189] opened 2022-07-12 15:41 UTC
Unable to Cancel the Orders as I am getting the error saying - Order not found : 284900843309368233228867881332425120710

onchainaddress:{espoXXdCqhP6oRPbP5avJhcZi6LNFyUCnDumF3cUPwops32FN}
![image](https://user-images.githubusercontent.com/94037805/178531946-874fa843-88da-4f76-9a8a-e7a9ce9fd33f.png)

**Comment by jaymansfield** [comment] 2022-07-12 15:45
#30

**Comment by pavankanteti** [comment] 2022-07-26 07:14
Closing as duplicate of #30

**Closed by pavankanteti** 2022-07-26 07:14 UTC
Labels: duplicate, Unconfirmed
