### ISSUE TITLE
Set of errors

### ISSUE THREAD

**Issue by shuterr** [Polkadex-Substrate/Polkadex-Open-Beta#240] opened 2022-08-24 16:51 UTC
1) Crashes from the account after refreshing the page. After refreshing the page you can't enter the account without creating a new tab - just can't see accounts with polkadot.js.
2) After a new login transactions work, but after 2-3 pieces stop working. Just no action does not happen neither sell, nor buy.
3) When going to the "purse" just a black screen.
4) A problem with UI, the bar is too compressed when scrolling (indicated in the video).
5) In some cases, it is impossible to enter numbers into orders.

All current problems are in the video. 
https://youtu.be/4aO_OZzYFMA

onchainaddress:{espUmw4HtYqby7bfM2QLhABMXB7HXuEq64riVXfACF3xefXKB}

**Comment by jaymansfield** [comment] 2022-08-25 12:48
I think most of these have been logged already.

#2 - cant refresh
#218 page breaks from too many decimal places made by the slider
#209 purse/wallet icon goes to blank page

**Comment by pavankanteti** [comment] 2022-11-16 07:28
1. This is fixed in the new account manager flow. Select an account as default and it should stay in session
2. Unable to reproduce
3. Option is removed
4. Will be replaced by a new slider implementation
5. Has been updated in the new UI
6. This has been fixed in a previous pr

**Closed by pavankanteti** 2022-11-16 07:28 UTC
Labels: Unconfirmed, Acknowledgement, Aug19-Oct2
