### ISSUE TITLE
Login after cache clearance

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#71] opened 2022-07-05 09:24 UTC
After cleareing Browser history, I am not seeing an option to Login. I can only manually type my password and account details are supposed to be shown and selected from the dropdown. The dropdown now doesn't show any account details. Neither can I manually give my account details to login. Import is throwing 500 error.

onchainaddress:{esp5dCFuAuPi6KD3HzhHWQGjgwiNvyWLp6qJW5EGgo7zkhRBJ}
![image](https://user-images.githubusercontent.com/94037805/177295101-03d4afe5-2e6a-417a-8c3f-214d153d36c6.png)

**Comment by pavankanteti** [comment] 2022-07-06 11:57
closing as duplicate of #5

**Closed by pavankanteti** 2022-07-06 11:57 UTC
Labels: duplicate, Unconfirmed
