### ISSUE TITLE
Wrong validation in the wallet deposit page

### ISSUE THREAD

**Issue by nashidahmed** [Polkadex-Substrate/Polkadex-Open-Beta#137] opened 2022-07-07 09:42 UTC
**Description** 

Incorrect form validation in wallet page.

**How to reproduce:**
1. Click my wallet and go to the wallet page. Default wallet gets set in the UI on the deposit page
2. Select a token to deposit
3. Error shows up for the Wallet field even though it is selected in the UI. The error goes upon reselecting the same wallet or a different wallet.

**Expected result:**
The "Required" error should not appear in the UI.

![orderbook-beta polkadex trade Incorrect validation](https://user-images.githubusercontent.com/37153833/177743480-46b3805f-e387-455b-a97d-9abb13c2d569.png)

onchainaddress:{esoia6ocj8jC4Wq2mSeiCsXf1Z3eHqx7oHQ8hK8iPgHUYAmeC}

**Comment by pavankanteti** [comment] 2022-07-12 05:55
closing as duplicate of #116

**Closed by pavankanteti** 2022-07-12 05:55 UTC
Labels: duplicate, Unconfirmed
