### ISSUE TITLE
Balance Not Updating Correctly 

### ISSUE THREAD

**Issue by Callynode** [Polkadex-Substrate/Polkadex-Open-Beta#289] opened 2022-09-29 20:17 UTC
**By raising this issue, I agree to the terms and conditions presented by Polkadex here:**[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf) 

**Description** 

When you place a limit order and there are price differences in the executed order, the balance will not update correctly. The mixing balance is rather locked up outside the orderbook. It appears in this instance, the balance update correlates (not correctly) with the order history rather than the trade history. 

As shown in the attached screenshot.  

I had a balance of 300FAU

I placed an order to buy 1 pdex at 55 FAU

The Order executed as follow:
0.80723030 at 30 FAU
remaining 0.19276970 at 55 FAU
Correct amount of FAU used to purchase 1 Pdex should have been 34.8192425
Hence, leaving the balance of 265.180758. 

But the balance on my wallet is 255.5917311665 FAU.
Also we have 20.1807575 locked after the trade which seems inaccessible.

![1](https://user-images.githubusercontent.com/114696843/193149370-fe429181-19b7-44eb-961a-3f751f94b426.png)
![2](https://user-images.githubusercontent.com/114696843/193149372-b18afb61-b567-45b6-a984-d2fdb19d4411.png)
![3](https://user-images.githubusercontent.com/114696843/193149377-799df983-f7f0-40f8-8243-72d5929bf3a9.png)
![4](https://user-images.githubusercontent.com/114696843/193149380-83d892cc-8eef-49ea-a56d-de4227498622.png)
![5](https://user-images.githubusercontent.com/114696843/193149382-5330a7c9-a5f2-4a46-b17d-3dbb805f9e62.png)
![6](https://user-images.githubusercontent.com/114696843/193149386-321c41ee-ed92-4117-8af6-2b1752faf899.png)

**Note** : Make sure you add the screenshot using Markdown syntax, For example: `![Alt Text](Screenshot Url)`

onchainaddress:{esnMUHkCkhAij8PPHjHEhgJ64J24Ad9YrF1rEtDLFfzyTe9m6}

**Comment by jaymansfield** [comment] 2022-09-29 23:39
Reported the locked funds issue in #275

**Comment by Zerocoinz** [comment] 2022-10-19 17:49
When you make an order which execute on different prices, the balance is not returned accurately, instead the remaining balance from the trade is locked up without any access to it.

**Comment by pavankanteti** [comment] 2022-11-17 14:12
Closing as duplicate of #275

**Closed by pavankanteti** 2022-11-17 14:12 UTC
Labels: Verified Author

**Comment by callizee** [comment] 2023-02-23 09:03
> Closing as duplicate of #275

Not exactly. This is different and still an issue last time I checked.
