### ISSUE TITLE
Orderbook Depth change is not working

### ISSUE THREAD

**Issue by mastervalidator** [Polkadex-Substrate/Polkadex-Open-Beta#112] opened 2022-07-06 14:33 UTC
By raising this issue, I agree to the terms and conditions presented by Polkadex here:[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf)

Description:
Orderbook Depth change is not working

![image](https://user-images.githubusercontent.com/108701680/177575357-e1c39180-48c4-45ea-b738-f7f5e172f8e1.png)

onchainaddress:{esqD5TsdP2UPmxsBZWEP5iTb73ZPW5mf9RSXsEoP6kw8bXW2Z}

**Comment by pavankanteti** [comment] 2022-07-08 14:13
duplicate of #11

**Closed by pavankanteti** 2022-07-08 14:13 UTC
Labels: Verified Author, FrontEnd, known issue
