### ISSUE TITLE
a possible memory leak when changing chart timeframe from 1min to 1h

### ISSUE THREAD

**Issue by mastervalidator** [Polkadex-Substrate/Polkadex-Open-Beta#109] opened 2022-07-06 14:14 UTC
By raising this issue, I agree to the terms and conditions presented by Polkadex here:[Terms and Conditions](https://github.com/Polkadex-Substrate/Polkadex-Open-Beta-Feedback/blob/master/Polkadex_Open_Beta_Program_-_Terms__Conditions.pdf)

Description
-possible memory leak when changing chart timeframe from 1min to 1h

https://user-images.githubusercontent.com/108701680/177571086-1e05a9d7-a9bc-48ca-90b6-1f187df1fa45.mp4

onchainaddress:{esqD5TsdP2UPmxsBZWEP5iTb73ZPW5mf9RSXsEoP6kw8bXW2Z}

**Comment by pavankanteti** [comment] 2022-07-08 14:20
closing as duplicate of #85

**Closed by pavankanteti** 2022-07-08 14:20 UTC
Labels: duplicate, Verified Author, FrontEnd, immediate fix
