### ISSUE TITLE
Orderbook orders mismatch

### ISSUE THREAD

**Issue by nashidahmed** [Polkadex-Substrate/Polkadex-Open-Beta#140] opened 2022-07-07 10:16 UTC
**Description** 

The PDEX/TDOT pair is showing incorrect values in the orderbook. The same orders appear in both the buy orders as well as the sell orders. The error seems to be due to the 1 TDOT sell order which is not getting filled even when trying to place a buy order for 1 TDOT. On trying to place a 1TDOT, the order goes straight to the open orders as seen in the screenshot below.

![orderbook-beta polkadex trade incorrect values orderbook](https://user-images.githubusercontent.com/37153833/177750117-b60ec597-30be-41e8-9ad5-45dd9338c30d.png)

onchainaddress:{esoia6ocj8jC4Wq2mSeiCsXf1Z3eHqx7oHQ8hK8iPgHUYAmeC}

**Comment by pavankanteti** [comment] 2022-07-12 05:58
duplicate of #6

**Closed by pavankanteti** 2022-07-12 05:58 UTC
Labels: duplicate, Unconfirmed
