### ISSUE TITLE
Unable to import wallet

### ISSUE THREAD

**Issue by jcbm123143** [Polkadex-Substrate/Polkadex-Open-Beta#48] opened 2022-07-04 19:19 UTC
<img width="960" alt="IMPORT WALLET" src="https://user-images.githubusercontent.com/22148449/177208132-87b71e74-7e30-478a-8106-2715e3f7a2d5.PNG">

onchainaddress:{esqyaynftRoreLfX2tsUN6rUzoN6zmoWYgnvzmcgV7yJvC9on}

**Comment by jaymansfield** [comment] 2022-07-04 22:52
Might be related to #5

**Comment by pavankanteti** [comment] 2022-07-06 11:26
Closing as duplicate of #5

**Closed by pavankanteti** 2022-07-06 11:26 UTC
Labels: duplicate, Unconfirmed
