### ISSUE TITLE
Checkmarks not working in Transactions grid.

### ISSUE THREAD

**Issue by DayalKS2** [Polkadex-Substrate/Polkadex-Open-Beta#120] opened 2022-07-06 15:08 UTC
Checkmarks not working in Transactions grid. All 3- Buy, Sell, Hide Other Pairs- are not working and filtering data

onchainaddress:{espoXXdCqhP6oRPbP5avJhcZi6LNFyUCnDumF3cUPwops32FN}
![image](https://user-images.githubusercontent.com/94037805/177583041-bd4ac812-01ad-4a45-add6-1a55442c4a35.png)

**Comment by pavankanteti** [comment] 2022-07-08 12:05
duplicate of #106

**Closed by pavankanteti** 2022-07-08 12:05 UTC
Labels: duplicate, Unconfirmed
