### ISSUE TITLE
Withdraw history table showing incorrect dates

### ISSUE THREAD

**Issue by jaymansfield** [Polkadex-Substrate/Polkadex-Open-Beta#342] opened 2022-10-07 14:13 UTC
Pending withdraws table showing incorrect date 

These withdraw requests were submitted last week... they are showing the current date/time as the date rather then when they were submitted. 

![image](https://user-images.githubusercontent.com/6218678/194574017-060ebee6-319c-452b-b95b-eae2881644e5.png)

onchainaddress:{esm99RRxKvainDsRR6UHRcju4vNnAw1ouZEw64Yfn12tc6HpQ}

**Comment by pavankanteti** [comment] 2022-10-10 08:43
Closing as duplicate of #295

**Closed by pavankanteti** 2022-10-10 08:43 UTC
Labels: duplicate, Verified Author, Aug19-Oct2
